/***************************************************************************//**
* \file YOLOV5N_tflm_model_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains YOLOV5N model data.
* Date: 2025-08-27 09:23:16.978803
*******************************************************************************
* \copyright
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.0.0.8656 based on TensorFlow 2.15.0 and ethos-u-vela 4.2.0
    ml-coretools-middleware-streaming 3.1.0.15301
    ml-coretools-tflm-qemu-images 3.1.0.15301
*/

#ifndef YOLOV5N_TFLM_MODEL_INT8X8_H
#define YOLOV5N_TFLM_MODEL_INT8X8_H

#include <stdint.h>
#define YOLOV5N_MODEL_BIN_LEN (1721008u)
#define YOLOV5N_ARENA_SIZE (890880u)

#ifdef CY_ML_MODEL_MEM
extern const uint8_t YOLOV5N_model_bin[];
#else
extern uint8_t YOLOV5N_model_bin[];
#endif // CY_ML_MODEL_MEM


#endif // YOLOV5N_TFLM_MODEL_INT8X8_H

